<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="SE Asia Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.0" os="" host="DESKTOP-H4RRNSP"><DocLocation><![CDATA[D:\ALM Octane Demo\Test Web GUI]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Test Web GUI]]></DName>
<Res><![CDATA[Test Web GUI]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="26" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:52]]></Time>
<TimeTick>1540264132</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:52]]></Time>
<TimeTick>1540264132</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hong"]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:52]]></Time>
<TimeTick>1540264132</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5b209229c674ccb69d0c9256"]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:53]]></Time>
<TimeTick>1540264133</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:53]]></Time>
<TimeTick>1540264133</TimeTick>
<NodeArgs eType="Replay" icon="32" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="30" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Sign-on: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:54]]></Time>
<TimeTick>1540264134</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123"]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:54]]></Time>
<TimeTick>1540264134</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="22" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5b20923078ca1717f0bbab7d"]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:55]]></Time>
<TimeTick>1540264135</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:55]]></Time>
<TimeTick>1540264135</TimeTick>
<NodeArgs eType="Replay" icon="32" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Sign-on: Mercury Tours.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:56]]></Time>
<TimeTick>1540264136</TimeTick>
<NodeArgs eType="Replay" icon="30" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Sign-on: Mercury Tours.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="30" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Sign-on: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10/23/2018 - 10:08:56]]></Time>
<TimeTick>1540264136</TimeTick>
<NodeArgs eType="Replay" icon="29" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="29" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/23/2018 - 10:08:52" eTime="10/23/2018 - 10:08:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="28" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="27" nRep="6" >
<Disp><![CDATA[Test Web GUI Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10/23/2018 - 10:08:50" eTime="10/23/2018 - 10:08:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="25" nRep="3" >
<Disp><![CDATA[Test Test Web GUI Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>